export const SPECIAL_CHARACTERS = [
  ["“", "Left double quotation mark"],
  ["”", "Right double quotation mark"],
  ["‘", "Left single quotation mark"],
  ["’", "Right single quotation mark"],
  ["–", "En dash"],
  ["—", "Em dash"],
  ["…", "Horizontal ellipsis"],
  ["•", "Bullet"],
  ["©", "Copyright sign"],
  ["®", "Registered sign"],
  ["™", "Trade mark sign"],
  ["°", "Degree sign"],
  ["€", "Euro sign"],
  ["£", "Pound sign"],
  ["¥", "Yen sign"],
  ["¢", "Cent sign"],
  ["±", "Plus-minus sign"],
  ["×", "Multiplication sign"],
  ["÷", "Division sign"],
  ["≠", "Not equal to"],
  ["≤", "Less-than or equal to"],
  ["≥", "Greater-than or equal to"],
  ["∞", "Infinity"],
  ["√", "Square root"],
  ["←", "Leftwards arrow"],
  ["↑", "Upwards arrow"],
  ["→", "Rightwards arrow"],
  ["↓", "Downwards arrow"],
  ["↔", "Left right arrow"],
  ["⇒", "Rightwards double arrow"],
];

export const EMOJI = [
  ["😀", "Grinning face"],
  ["😂", "Face with tears of joy"],
  ["😊", "Smiling face with smiling eyes"],
  ["😍", "Smiling face with heart-eyes"],
  ["🤔", "Thinking face"],
  ["😢", "Crying face"],
  ["😡", "Enraged face"],
  ["👍", "Thumbs up"],
  ["👎", "Thumbs down"],
  ["👏", "Clapping hands"],
  ["🙌", "Raising hands"],
  ["🙏", "Folded hands"],
  ["👋", "Waving hand"],
  ["💪", "Flexed biceps"],
  ["❤️", "Red heart"],
  ["⭐", "Star"],
  ["✅", "Check mark button"],
  ["❌", "Cross mark"],
  ["🔥", "Fire"],
  ["🎉", "Party popper"],
  ["💡", "Light bulb"],
  ["📌", "Pushpin"],
  ["📅", "Calendar"],
  ["⏰", "Alarm clock"],
];

export function formatCurrentDateTime(
  date = new Date(),
  locales,
  options = {},
) {
  return new Intl.DateTimeFormat(locales, {
    dateStyle: "medium",
    timeStyle: "short",
    ...options,
  }).format(date);
}
